/**
 * Advertisement slots. Every slot reserves its exact pixel dimensions so
 * creatives never shift the layout. Creatives are dummy SVGs generated by
 * `node scripts/make-ad-placeholders.mjs` into public/ads/.
 */

export type AdSizeKey =
  | "leaderboard"
  | "billboard"
  | "mpu"
  | "halfPage"
  | "mobileBanner"
  | "inFeed";

export interface AdSize {
  width: number;
  height: number;
  label: string;
  /** Fluid sizes (in-feed square) stretch to their column instead of capping at `width`. */
  fluid?: boolean;
}

export const adSizes: Record<AdSizeKey, AdSize> = {
  leaderboard: { width: 728, height: 90, label: "Leaderboard" },
  billboard: { width: 970, height: 250, label: "Billboard" },
  mpu: { width: 300, height: 250, label: "MPU" },
  halfPage: { width: 300, height: 600, label: "Half page" },
  mobileBanner: { width: 320, height: 100, label: "Mobile banner" },
  inFeed: { width: 600, height: 600, label: "In-feed", fluid: true },
};

export interface AdCreative {
  /** Creative for the slot's primary `size`. */
  src: string;
  href: string;
  alt: string;
  sponsorName: string;
  /** Creatives for the alternate sizes (`mobileSize`, `tabletSize`). */
  srcBySize?: Partial<Record<AdSizeKey, string>>;
}

export interface AdSlotConfig {
  label: string;
  /** Size at ≥ lg (or ≥ md when no tabletSize is set). */
  size: AdSizeKey;
  /** Optional size for md ≤ width < lg. */
  tabletSize?: AdSizeKey;
  /** Optional size below md. Without it the primary size scales down fluidly. */
  mobileSize?: AdSizeKey;
  enabled: boolean;
  /** One line for the dashboard: where on the site the slot appears. */
  where: string;
  creative: AdCreative;
}

export type AdSlotKey =
  | "home.belowHero"
  | "home.midMosaic"
  | "home.beforeListen"
  | "section.topLeaderboard"
  | "section.rail"
  | "section.inFeed"
  | "article.rail"
  | "article.inBody"
  | "article.belowBody"
  | "listing.top"
  | "listing.inFeed"
  | "podcast.rail";

/* ------------------------------------------------------------------ */
/*  Dummy creatives                                                    */
/* ------------------------------------------------------------------ */

type Variant = "a" | "b";

/**
 * Sponsor per variant, mirrored from scripts/make-ad-placeholders.mjs:
 * banner-shaped sizes share one sponsor per variant so a slot that swaps
 * sizes by breakpoint keeps the same advertiser; the rail boxes carry the
 * other two names.
 */
const SPONSORS = {
  banner: {
    a: { name: "Himalaya Organics", line: "Seasonal Harvest", href: "https://example.com/himalaya-organics" },
    b: { name: "Ganga Tours", line: "Char Dham 2026", href: "https://example.com/ganga-tours" },
  },
  box: {
    a: { name: "Doon Valley Realty", line: "Homes above the haze", href: "https://example.com/doon-valley-realty" },
    b: { name: "Bharat Fintech", line: "UPI for everyone", href: "https://example.com/bharat-fintech" },
  },
} as const;

const family = (size: AdSizeKey) => (size === "mpu" || size === "halfPage" ? "box" : "banner");

function dummy(variant: Variant, size: AdSizeKey, ...alternates: AdSizeKey[]): AdCreative {
  const file = (s: AdSizeKey) => `/ads/${s}-${variant}.svg`;
  const sponsor = SPONSORS[family(size)][variant];
  const srcBySize: Partial<Record<AdSizeKey, string>> = {};
  for (const s of alternates) srcBySize[s] = file(s);
  return {
    src: file(size),
    href: sponsor.href,
    alt: `${sponsor.name} — ${sponsor.line} (advertisement)`,
    sponsorName: sponsor.name,
    srcBySize,
  };
}

/* ------------------------------------------------------------------ */
/*  Slots                                                              */
/* ------------------------------------------------------------------ */

export const adSlots: Record<AdSlotKey, AdSlotConfig> = {
  "home.belowHero": {
    label: "Home · below hero",
    size: "billboard",
    tabletSize: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Front page, directly under the hero",
    creative: dummy("a", "billboard", "leaderboard", "mobileBanner"),
  },
  "home.midMosaic": {
    label: "Home · between Mosaic and Watch",
    size: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Front page, between the story mosaic and Watch",
    creative: dummy("b", "leaderboard", "mobileBanner"),
  },
  "home.beforeListen": {
    label: "Home · before Listen",
    size: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Front page, above the Listen band",
    creative: dummy("a", "leaderboard", "mobileBanner"),
  },
  "section.topLeaderboard": {
    label: "Section · top",
    size: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Section pages, above the story list",
    creative: dummy("b", "leaderboard", "mobileBanner"),
  },
  "section.rail": {
    label: "Section · right rail",
    size: "halfPage",
    enabled: true,
    where: "Section pages, sticky right rail (desktop only)",
    creative: dummy("a", "halfPage"),
  },
  "section.inFeed": {
    label: "Section · in feed",
    size: "leaderboard",
    mobileSize: "inFeed",
    enabled: true,
    where: "Section pages, inside the story list",
    creative: dummy("a", "leaderboard", "inFeed"),
  },
  "article.rail": {
    label: "Article · right rail",
    size: "halfPage",
    enabled: true,
    where: "Article pages, sticky right rail (desktop only)",
    creative: dummy("b", "halfPage"),
  },
  "article.inBody": {
    label: "Article · in body",
    size: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Article pages, between the first paragraphs",
    creative: dummy("a", "leaderboard", "mobileBanner"),
  },
  "article.belowBody": {
    label: "Article · below body",
    size: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Article pages, after the story",
    creative: dummy("b", "leaderboard", "mobileBanner"),
  },
  "listing.top": {
    label: "Listing · top",
    size: "leaderboard",
    mobileSize: "mobileBanner",
    enabled: true,
    where: "Breaking and Blogs listings, above the list",
    creative: dummy("a", "leaderboard", "mobileBanner"),
  },
  "listing.inFeed": {
    label: "Listing · in feed",
    size: "leaderboard",
    mobileSize: "inFeed",
    enabled: true,
    where: "Breaking and Blogs listings, inside the list",
    creative: dummy("b", "leaderboard", "inFeed"),
  },
  "podcast.rail": {
    label: "Podcasts · rail",
    size: "mpu",
    enabled: true,
    where: "Podcasts page, right rail",
    creative: dummy("a", "mpu"),
  },
};

export function getAdSlot(key: AdSlotKey): AdSlotConfig {
  return adSlots[key];
}
